name: Generate Language

run-name: ' Generate Language: ${{ inputs.Language }} (${{ inputs.Generate }})'

on:
  workflow_call:
    inputs:
      OpenAIKey:
        required: true
        type: string
      Language:
        required: true
        type: string
      Generate:
        required: true
        type: string
      Extension:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      OpenAIKey:
        description: 'OpenAI API Key'
        required: true
        type: string
      Language:
        description: 'Language to generate examples for'
        required: true
        type: string
      Generate:
        description: 'Generate examples for the language'
        options:
          - all
          - patterns
          - principles
        required: true
        type: choice
      Extension:
        description: 'File extension for the generated examples'
        required: true
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Build Language
        env:
          OPENAI_API_KEY: ${{ inputs.OpenAIKey }}
        run: |
          npm install

          node ./.scripts/esm/build-language-examples.js -l ${{ inputs.Language }} -g ${{ inputs.Generate }} -e ${{ inputs.Extension }} --dry-run

      - name: Push Language Branch
        env:
          TARGET_REPO: solidref/solidref
        run: |
          set -ex
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

          # Clone the GitHub Pages repository
          git clone https://${{secrets.GH_TOKEN}}@github.com/${TARGET_REPO}.git /tmp/solidref
          cp -rdf ./yaml/lang/${{ inputs.Language }} /tmp/solidref/yaml/lang

          cd /tmp/solidref/yaml/lang
          git checkout -b ${{ inputs.Language }}_lang

          git add .
          git commit -m "${{ inputs.Language }} language"
          git push origin ${{ inputs.Language }}_lang
